version: "3.4"

services:
    gogs:
        container_name: repository-git
        environment:
            - RUN_CROND=true
        image: gogs/gogs:${GOGS_VERSION}
        ports:
            - "18082:3000"
            - "28030:22"
        restart: always
        volumes:
            - ./git/data/conf/app.ini:/data/gogs/conf/app.ini
            - gogs-data:/data/gogs
            - gogs-repositories:/data/git/gogs-repositories

volumes:
    gogs-data:
        driver: local
        name: gogs-${GOGS_VERSION}-data
    gogs-repositories:
        driver: local
        name: gogs-${GOGS_VERSION}-repositories-data
